### ISSUE TITLE
sql query error

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_groups#1]
when I try to run the sql query it tells me that:
Error: 150 "Foreign key constraint is incorrectly formed"

What do I have to change ?

My query:
CREATE TABLE `groups` (
  `charid` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `rank` int(11) NOT NULL,
  UNIQUE KEY `name` (`name`,`charid`),
  KEY `FK_groups` (`charid`),
  CONSTRAINT `groups_ibfk_1` FOREIGN KEY (`charid`) REFERENCES `users` (`identifier`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB;

**Comment by thelindat** [comment]
You would need to change either ESX to use incrementing ids instead, or use varchar here.

**Comment by maxcamorra** [comment]
What exactly I have to change to varchar ?

**Comment by thelindat** [comment]
If you don’t know how sql works I can’t recommend using this

**Comment by maxcamorra** [comment]
problem is that the inv now works with groups and not jobs anymore so i have to use this script or not..

**Comment by thelindat** [comment]
That’s not how it works otherwise I’d have instructions to use this resource as well as dependency on it. Esx jobs remap to the correct format.
